name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clonning
        run: git clone https://github.com/nomansarwar84/django-notes-app.git
      - name: Build
        run: docker build . -t notes-app
      - name: Deploy
        run: docker run -d -p 8000:8000 notes-app
